config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :products do
    resources :comments
  end

  resources :users

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'users/sign_up'

  post 'static_pages/thank_you'

  resources :orders, only: [:index, :show, :create, :destroy]

  root 'static_pages#landing_page'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :comments
	validates :name, presence: true

	def average_rating
	comments.average(:rating).to_f
	end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.where("name LIKE ?", "%#{search_term}%")
    else
      @products = Product.all
    end

    respond_with @products
  end



  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 2)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comment.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
            <p><div class="rated" data-score="<%= comment.rating %>"></div></p>
            <p><%= comment.body %></p>
<p>

    <% if signed_in? && current_user.admin? %>
        <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
</p>
        </div>
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h4>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
  <%= f.label :color, :colour %><br>
  <%= f.text_field :colour %>
  </div>
  <div class="field">
  <%= f.label :price %><br>
  <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-info btn-sm" %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
<div class="newcomment">

  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>

    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>

    </p>

    <p>
      <div class="rating"></div>
    </p>

    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>

<% end %>
</div>

app/views/products/_product.html.erb
<% cache @products do %>

<div class="container">
  <div class="products_row product_section">
    <% @products.each do |product| %>
    <div class="col-sm-2 col-md-4 under_product">
      <%= image_tag(product.image_url, class: "img-responsive") %>
      <h4><%= link_to product.name, product %></h4>
      <strong><p><%= product.price %></p></strong>
      <p><%= link_to 'View', product %> <%= link_to 'Edit', edit_product_path(product) %> <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>

    </div><!-- /col -->
    <% end %>
  </div>
</div>

<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Products</h2>

<% cache(cache_key_for_products) do %>

<%= render 'product' %>

<% end %>

<br>

<br><br>
<p class="under_product">
<%= link_to 'New Product', new_product_path %>
</p>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
</h2>

<br><br>



<div class="container-fluid">
  <div class="row">

    <div class="col-md-4">
      <%= image_tag(@product.image_url, width: "350", class: "img-zoom", data_zoom_image: @product.image_url) %>
    </div>

    <div class="col-md-8 product_deats">
<% cache @product do %>
    <h3><%= @product.name %></h3>

    <h5><%= @product.description %></h5>
    <h5>
        <strong>Price:</strong>
        <%= @product.price %>
    </h5>
<% end %>

        <p>Average Rating: <div class="rated product_deats" data-score="<%= @product.average_rating %>"></div> </p>
        <%= render 'new_comment' %>

        <p><%= form_tag "/payments/create" do %>
        <%= render partial: "shared/stripe_checkout_button" %>
        <% end %></p>
        <%= hidden_field_tag(:product_id, @product.id) %>
    </div>




<div class="row">
    <div class="col-md-8 col-md-offset-2">
<%= render 'comment' %>
    <p><%= will_paginate @comments, :page_links => false %></p>

    </div>
</div>





</div>
</div>